### ISSUE TITLE
updateAgenda.js Could not find module note dayjs/plugin/isBetween

### ISSUE THREAD

**Issue by giantbirdicus** [BeatLink/trilium-scripts#4]
I followed the myDay readme and got those Scripts working. I feel I'm following the Agenda readme correctly but I'm having issues with getting the updateAgenda.js script to run.

I get this message:
_Execution of JS note "updateAgenda.js" with ID FyQKp9RnLDz5 failed with error: Load of script note "updateAgenda.js" (FyQKp9RnLDz5) failed with: Could not find module note dayjs/plugin/isBetween_

using trilium-windows-x64-0.60.4

I do not have much JavaScript experience. Any help will be appreciated.
Thank you

**Comment by giantbirdicus** [comment]
NoteId copy paste error. Fixed the NoteId copy/paste mistake and error went away.

**Comment by DTHriven6** [comment]
#7
