### ISSUE TITLE
Mobile View: where to find "scriptNoteId"

### ISSUE THREAD

**Issue by tiritibambix** [BeatLink/trilium-scripts#5]
Hello.

I really want to learn using Trilium, but I'll mostly use it on my phone. So I wanted to give the script a try.

I am not familiar at all with Trilium nor JS, so I have a couple questions.

Where can I find the "scriptNoteId" for each script and how should I write it in the SetupButtons notes ?

Also, are labels to be added in the "Owned attributes" tab ?

Thanks for your help

**Comment by BeatLink** [comment]
For each javascript script that you add, the note id can be found under the note info tab. Copy that to its respective area in the setupbuttons.js scrip

**Comment by tiritibambix** [comment]
> For each javascript script that you add, the note id can be found under the note info tab. Copy that to its respective area in the setupbuttons.js scrip

Finally found that, thank you. I got the buttons showing up on the left but they do nothing. I am in desktop mode.

Are labels to be added in the "Owned attributes" tab ? Looks like yes but I want to be sure I'm doing things the right way.
See my notes if something is not right:
![bubbler.jpg](https://clip.steph.click/-sTphxpmjui/triliumscripts1.png)

Also, I got an error in my SetupButtons.js at line 7 : `parsing error: Unexpected token function`. Is this normal ?
![bubbler.jpg](https://clip.steph.click/-bNyZJ9U5Sd/triliumscripts2.png)

**Comment by BeatLink** [comment]
Are the note types set to JS Frontend?

**Comment by tiritibambix** [comment]
Yes, they are :
![image](https://clip.steph.click/-CCAuu3yKxH/triliumscripts3.png)

**Comment by BeatLink** [comment]
For the setupbuttons.js as well?

**Comment by tiritibambix** [comment]
For all 5

**Comment by BeatLink** [comment]
What version of trilium are you using?

**Comment by tiritibambix** [comment]
App version: | 0.61.13
DB version: 227
Sync Version: 31
Build date : 2023-11-06T00:21:41+01:00
Build revision : [531e9d4aff47b7e8332420645546d25ab28acf85](https://github.com/zadam/trilium/commit/531e9d4aff47b7e8332420645546d25ab28acf85)

**Comment by BeatLink** [comment]
That is weird

**Comment by BeatLink** [comment]
If the 4 buttons show up that means the buttons are loaded though. What happens if you click the cellphone button then the left arrow button?

**Comment by tiritibambix** [comment]
Nothing. It happens nothing.

![video](https://clip.steph.click/-MfhYqin6py/Record_2023-11-11-20-48-18.mp4)

**Comment by tiritibambix** [comment]
Would you be curious to access a test instance of mine with the exact same config ?

**Comment by BeatLink** [comment]
Sorry for the late reply, It's been a hectic week but sure I can take a look

**Comment by tiritibambix** [comment]
Sure no problem.
You can access my test instance [here](https://test.steph.click). The password is `test`

**Comment by BeatLink** [comment]
Found the problem. You forgot to add two of the files:

https://github.com/BeatLink/trilium-scripts/blob/main/Mobile%20View/MobileView.css

That does the actual changes to the UI

https://github.com/BeatLink/trilium-scripts/blob/main/Mobile%20View/SetHTMLMeta.js

This sets up the scaling for mobile devices so everything isnt so tiny in desktop mode. Add em both and give it another try

**Comment by tiritibambix** [comment]
Yes ! It's working. I totally misinterpreted the instructions.
Thanks for your work and thanks for your time. Hope you'll get some good rest after this week :)

**Comment by BeatLink** [comment]
No prob, and thanks! :)
